### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by sharicov** [bithatch/snake#1]
Kubuntu 20.10
Installed 2.8.0 drivers, added plugdev user, rebooted
Getting Unknown Error when running Snake
Output in terminal:
`snake-razer/bin/snake 
(java:2210): Gdk-WARNING **: 10:51:40.585: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
[AWT-EventQueue-0] WARN dorkbox.systemTray.SystemTray - Please disable tooltips, as they are not consistent across all platforms and tray types.
org.freedesktop.dbus.errors.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getDeviceImage is not a valid method of interface razer.device.misc
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at dbus.java/org.freedesktop.dbus.errors.Error.getException(Error.java:157)
        at dbus.java/org.freedesktop.dbus.errors.Error.throwException(Error.java:187)
        at dbus.java/org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:164)
        at dbus.java/org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:228)
        at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy22.getDeviceImage(Unknown Source)
        at uk.co.bithatch.snake.lib.backend.openrazer/uk.co.bithatch.snake.lib.backend.openrazer.NativeRazerDevice.getImage(NativeRazerDevice.java:1143)
        at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.Tray.addDevice(Tray.java:83)
        at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.Tray.rebuildMenu(Tray.java:276)
        at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.Tray.adjustTray(Tray.java:254)
        at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.Tray.lambda$new$8(Tray.java:70)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by brett-smith** [comment]
Ah. I saw this error myself yesterday. I believe it is down to the version of OpenRazer being used. Snake was built against the current stable version 2.8.0, but it appears that OpenRazer are deprecating some methods. https://github.com/openrazer/openrazer/commit/83d275d8584fcc71b8eab299c799240faa5d05a3.

I have a fix ready, but just to confirm, what version of OpenRazer are you using?

**Comment by brett-smith** [comment]
I have just pushed an update that should fix this. If you have automatic updates turned on, you shouldn't need to do anything other than restart. You will be the first person other than me to use the updater, so I hope it goes well :)

**Comment by sharicov** [comment]
Seems like it working now, thanks a lot!
Looks great!
Is it possible to customize the effects? (to make wave effect slower,
change direction besides left to right/right to left)?

**Comment by brett-smith** [comment]
Great! Thanks for reporting back.

And to answer your question, sadly no, not at the moment. 

Long answer ... The effects provided are the basic ones provided by the hardware itself. OpenRazer does provide the ability to do custom effects, but the only one I have come  across is 'Ripple', and that may not be supported on your hardware (Snake will show it if its supported). A question like this may be directed at the OpenRazer project, as you'll find other OpenRazer based apps have the same issue unless they add additional effects on top. 

And some hope  ... I do plan to make it possible to do this in Snake even if OpenRazer can't. The 'Matrix' screen can currently only set up static lights. I plan to make it possible to build your own custom effects from this screen, possibly via a scripting system that will allow users to share their custom effects with others. Watch this space :)

Closing this issue, please create another if you have any further questions or bugs.
