### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Xavron** [bithatch/snake#11]
I'm removing openrazer so will not be providing more info. Just letting you know about the crash. Maybe will try again someday but for now won't be.

In addition to below, the Snake UI is frozen and displays a message with the part below: Cannot calibrate this device type (DIGITAL_JOYSTICK). Then it force closes after a short time.

Apr 25, 2021 6:51:46 PM uk.co.bithatch.snake.ui.macros.MacroManager addMacroDevice
WARNING: No input device path found for razer device Razer Viper Ultimate (Wireless).
Apr 25, 2021 6:51:46 PM uk.co.bithatch.snake.ui.App createMainScene
SEVERE: Failed to initialize.
java.lang.IllegalArgumentException: Cannot calibrate this device type (DIGITAL_JOYSTICK)
	at uk.co.bithatch.macrolib/uk.co.bithatch.macrolib.UInput.loadCalibration(UInput.java:378)
	at uk.co.bithatch.macrolib/uk.co.bithatch.macrolib.UInput.open(UInput.java:433)
	at uk.co.bithatch.macrolib/uk.co.bithatch.macrolib.MacroSystem.open(MacroSystem.java:788)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.macros.MacroManager.start(MacroManager.java:132)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.App.createMainScene(App.java:536)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.App.start(App.java:455)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl$$Lambda$193/0x00000000c014ecd8.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$188/0x00000000c014cdf8.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$191/0x00000000c014e920.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$190/0x00000000c014d038.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication$$Lambda$179/0x00000000bc081858.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:853)
	
https://github.com/bithatch/macrolib/blob/master/src/main/java/uk/co/bithatch/macrolib/UInput.java#361

From the looks of it, the mouse is being thrown into the joystick code blocks. I don't know if that's intentional but open() appears to have deviceType == TargetType.MOUSE so I would think something isn't correct there. Or its getting something else that it should ignore and fail softly.

**Comment by brett-smith** [comment]
Thanks for the report. It appears this happens when `jscal` (from the `joystick` package) or `jstest-gtk` are not installed. I'll get this fixed, but in the meantime as a work around, you could install these.

**Comment by brett-smith** [comment]
Fixed, update released.
